name 'selinux'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures selinux'
long_description 'Installs/Configures selinux'
version '0.1.0'
